apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: riker-snakes-ingress
  namespace: team-riker
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: riker-snakes.{{ .Values.spec.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: snakes
            port: 
              number: 80
        
        
