spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Amit-Naudiyal/eks-blueprints-workloads
    targetRevision: amit-project
  ingress:
    host: dev.example.com