apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-troi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: team-troi
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/aws-samples/ssp-eks-workloads
    path: teams/team-troi/prod
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true