apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: riker-ingress
  namespace: team-riker
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: riker.dev.kcaws.people.aws.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kustomize-guestbook-ui
            port: 
              number: 80
        
        